### ISSUE TITLE
casting Input and Action

### ISSUE THREAD

**Issue by digitalmagus** [NMAI-lab/JLOAF#88]

**Comment by digitalmagus** [comment]
I'm getting a number of compilation errors in both org.experiment.simulation, as well as my own instances of AtomicInput or SImilarityMetric classes. Example:

chad@ubuntu:~/github/NMAI/JLOAF/bin$ java experiment.simulation 
Exception in thread "main" java.lang.ClassCastException: org.jLOAF.inputs.AtomicInput cannot be cast to org.jLOAF.inputs.StateBasedInput
	at org.jLOAF.casebase.CaseBase.add(CaseBase.java:55)
	at experiment.simulation.main(simulation.java:57)

Thoughts?

**Comment by digitalmagus** [comment]
It appears the CaseBase.add called by the simulator is automatically casting to StateBased input containing a ComplexInput (and Action). Should the example simulator first create a ComplexInput, or alternatively, use CreateThenAdd() instead?

**Comment by sachag678** [comment]
Yes, It should use CreateThenAdd(). This is an oversight on my part. I didn't update the code after we made changes. I do suggest checking out the https://github.com/sachag678/JLOAF/wiki/How-to-set-it-up-Example, for a more up to date example.
