### ISSUE TITLE
Real time creation of StateBasedInputs

### ISSUE THREAD

**Issue by sachag678** [NMAI-lab/JLOAF#89]
There are many steps required to create a stateBasedInput in real time.

You have to take a complexInput, add it to a stateBasedInput. Then predict an action, then create a case with the statebasedInput and the action predicted. Create a new stateBasedInput and add this case to it.
Then get the new complexInput and add it to the stateBasedInput. 

This manual cycle is very complicated and there must be an easier way to do it. 

Look into a structure that allows for this, or makes this process easier.

**Comment by sachag678** [comment]
@digitalmagus

**Comment by sachag678** [comment]
I created the issue, so we can eventually look into solving the manual creation we had to do this morning.

**Comment by digitalmagus** [comment]
Assigned to myself; still looking into the best way to handle.

**Comment by loushiano** [comment]
I know that creating the statebased input on the fly looks complicated given the current jloaf setup, but here's my approach to tackle the problem. Note that it might not be the best solution:
Case c= null;
for(//here is where you loop to get the input from the environment){
StateBasedInput st = new StateBasedInput(getInputFromEnvironment(),c);
 Action a=predictTheAction(st, casebase);
c= new Case(st,a);
}
